// -------------------------------------------------------------------------------- 
// Class : Warden
// Sheet : Warden
// -------------------------------------------------------------------------------- 
// DisplayName :
"P9005417637" "Warden"
// DisplayHelp :
"P3869696969" "The Warden tends to assist his allies in the fray, where his close quarters combat abilities are able to shine in tandem with his considerable support capabilities. He will unleash substantial melee damage while supporting allies and weakening foes in the immediate area. The Warden's alertness and ability to evade attacks depends on how many allies he has fighting alongside him, gaining a bonus to melee and ranged defense when alone, which is sacrificed for greater protection against AoEs in larger teams."
// -------------------------------------------------------------------------------- 
